(define (fact n)
    (define (fact n acc)
        (if (= n 0)
            acc
            (fact (- n 1) (* acc n))
        )
    )
    (fact n 1)
)

;; https://en.wikipedia.org/wiki/Call-with-current-continuation

(define (fib-gen)
    (define f-2 0)
    (define f-1 1)
    (define f 1)

    (define (get-next return)
        (set! return (call/cc (lambda (resume-here)
            (set! get-next resume-here)
            (return f-2)
        )))
        (set! return (call/cc (lambda (resume-here)
            (set! get-next resume-here)
            (return f-1)
        )))
        (define (loop)
            (set! return (call/cc (lambda (resume-here)
                (set! get-next resume-here)
                (set! f-2 f-1)
                (set! f-1 f)
                (set! f (+ f-2 f-1))
                (return f-1)
            )))
            (loop)
        )
        (loop)
    )

    (lambda ()
        (call/cc get-next)
    )
)

(define fib (fib-gen))

(define (loop x)
    ; (sleep 1)
    (display (fib))
    (newline)
    (if (> x 0)
        (loop (- x 1))
    )
)

(loop 30)
